### ISSUE TITLE
Segmentation fault - choosing one variable(GLW) for 20 years

### ISSUE THREAD

**Issue by ajijohn** [trenchproject/tecor-monitor#4]
Coordinates: 
(0)	1
(0)	writing data to csv
fatal:NclMalloc Failed:[errno=12]
Segmentation fault (core dumped)
Child returned 139
Traceback (most recent call last):
  File "monitor.py", line 205, in <module>
    s.run()
  File "/usr/lib/python3.4/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "monitor.py", line 160, in check_new
    "-" + request_lkup['enddate'], request_lkup['email'])
  File "/usr/lib/python3.4/enum.py", line 222, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.4/enum.py", line 457, in __new__
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 139 is not a valid ErrorMessages
ubuntu@ip-172-31-30-113:~/tecor-monitor$ git status
On branch master

**Comment by levyofi** [comment]
Does segmentation fault happen just when writing to the file or when reading the data from the netcdf files?
